### ISSUE TITLE
restore-builder: fix logic that prepares resources before import

### ISSUE THREAD

**Issue by mmilata** [projectatomic/osbs-client#407]
Don't strip status.lastVersion from buildconfigs: causes build numbers for each restored buildconfig to start from 1, which then clashes with name of a restored build.

Typo: lastTrigerredImageID -> lastTriggeredImageID.

Review why are we stripping spec.triggers.*.imageChange.lastTriggeredImageID.

**Comment by mmilata** [comment]
Perhaps @soltysh could shine some light on this. When doing backup of buildconfigs, should we throw away the values of `spec.triggers.*.imageChange.lastTriggeredImageID`? [Docs](https://docs.openshift.org/latest/rest_api/openshift_v1.html#v1-imagechangetrigger) say this attribute is "used internally", and `oc export` drops it so I'd be inclined to drop it as well, however I'm not sure what this means for rebuilds. Can we accidentally start a rebuiuld this way?.

**Comment by soltysh** [comment]
@mmilata `imageChange.lastTriggeredImageID` informs the controller what was the imageID when the trigger last time fired. If your export does not contain that value it means that repush of the same image (same imageID) will trigger a rebuild. Whereas if that value would be present no rebuild will happen. The reason for why it's being removed is simple, if you re-creating a `BuildConfig` in a different instance/project/etc. (which is why you do the export, right ;)) then the re-build is fine. In your specific case, the rebuild is not desirable, iuuc. So I'd advice you to have it included in the backup as well. 
Lastly, why would you be interested in doing such backup? I might be missing some piece of puzzle, mind shedding some light?

**Comment by mmilata** [comment]
@soltysh, thanks for the info! 

As of why, we wanted to be able to back up just the OpenShift resources we are using (that are not created by Ansible). IIRC we used this in the past to migrate the builder from one machine to another.

Is there an official (or just better) way of backing up the cluster we should be using instead?

**Comment by soltysh** [comment]
Generally, the recommended strategy is to backup entire etcd data, which holds all the relevant information. I don't think there exists any specific way of backing up just the selected objects. But if you're interested I'd go with plain `oc get bc -o yaml`, which will dump you all the BC (with all the metadata), at least you don't care what's missing there, since actually more than you need will be there. But if it's for backup, it's much more relevant, imho.
