### ISSUE TITLE
Set 'openshift.io/build.start-policy' label for scratch builds

### ISSUE THREAD

**Issue by vrutkovs** [projectatomic/osbs-client#506]
Related: #504 

I think its safe to set this label to `Parallel`

**Comment by mmilata** [comment]
This won't do anything since scratch builds have no BuildConfig (`openshift.io/build-config.name` annotation): https://github.com/openshift/origin/blob/v1.3.2/pkg/build/controller/policy/policy.go#L131

In fact, having no BuildConfig means that `HandleComplete` doesn't try to find next build and therefore doesn't do the expensive build list operation.

**Comment by vrutkovs** [comment]
Ah, okay. Closing this one then
